/*

FSM15 - FREE STATUS MONITOR


DIESES SCRIPTPROJEKT UND ALLE ZUGEHÖRIGEN DATEN SIDN FREIE SOFTWARE MIT OFFENEM QUELLCODE.

ES GELTEN DIE LIZENZBEDINGUNGEN WIE UNTER DEM MODUL "LICENSE.GS" BESCHRIEBEN UND ZUSÄTZLICH NOCH FOLGEDEN FESTLEGUNG:
********************************************************************************************************************************
* AUCH BEI ERWEITERUNG UND/ODER VERÄNDERUNG DIESER SOFTWARE IST DER HINWEIS AUF DEN INITIALEN ERSTELLER BEIZUBEHALTEN UND DARF *
* NICHT GELÖSCHT WERDEN. BETROFFENE STELLEN IM QUELLCODE SIND GEKENNZEICHNET (LINKS AUF DEN WEBSITEN).                         *
********************************************************************************************************************************

DIE VERBREITUNG UND WEITERENTWICKLUNG UNTER DEN LIZENZBEDINGUNGEN IST AUSDRÜCKLICH GESTATTET UND ERWÜNSCHT.

KONTAKT ZUM AUTHOR PER MAIL.
freestatusmonitor@gmail.com

AUSFÜHRLICHE INSTALLATIONS- UND BEDIENUNGSANLEITUNG UNTER:
https://goo.gl/rufvsc

SOURCECODE UND ISSUETRACKER FÜR ERWEITERUNGEN  BEI GITHUB:
https://github.com/diedder/fsm15

APPEN, MÄRZ 2017
LARS BREMER (diedder)

*/